export const todos = [
  {
    id: 1,
    name: "Buy groceries",
    caption: "Go to the market and buy groceries for the week",
    category: "Groceries",
    isCompleted: false,
  },
  {
    id: 2,
    name: "Do laundry",
    caption: "Wash and fold laundry",
    category: "Choreasdgkmadlkmglkmadglkmadlkmglmkadgs",
    isCompleted: true,
  },
  {
    id: 3,
    name: "Call mom",
    caption: "Check in with mom and catch up on news",
    category: "Personal",
    isCompleted: false,
  },
  {
    id: 4,
    name: "Pay bills",
    caption: "Pay monthly bills online or by mail",
    category: "Finances",
    isCompleted: false,
  },
  {
    id: 5,
    name: "Schedule dentist appointment",
    caption: "Call dentist office and schedule an appointment",
    category: "Health",
    isCompleted: true,
  },
  {
    id: 6,
    name: "Go for a run",
    caption: "Run for 30 minutes around the neighborhood",
    category: "Fitness",
    isCompleted: false,
  },
  {
    id: 7,
    name: "Read a book",
    caption: "Read for 30 minutes before bed",
    category: "Personal Development",
    isCompleted: false,
  },
  {
    id: 8,
    name: "Organize closet",
    caption: "Sort through clothes and organize closet",
    category: "Cleaning",
    isCompleted: false,
  },
  {
    id: 9,
    name: "Cook dinner",
    caption: "Prepare a healthy and tasty dinner at home",
    category: "Cooking",
    isCompleted: true,
  },
  {
    id: 10,
    name: "Watch movie",
    caption: "Watch a movie or TV show for entertainment",
    category: "Entertainment",
    isCompleted: false,
  },
  {
    id: 11,
    name: "Make a to-do list",
    caption: "Create a list of tasks for the day or week",
    category: "Productivity",
    isCompleted: false,
  },
  {
    id: 12,
    name: "Plan vacation",
    caption: "Research and plan a vacation for the future",
    category: "Travel",
    isCompleted: false,
  },
  {
    id: 13,
    name: "Do a home workout",
    caption: "Do a 20-minute workout at home",
    category: "Fitness",
    isCompleted: false,
  },
  {
    id: 14,
    name: "Learn a new recipe",
    caption: "Find and try a new recipe for a meal or snack",
    category: "Cooking",
    isCompleted: false,
  },
  {
    id: 15,
    name: "Write in journal",
    caption: "Reflect on the day and write in a personal journal",
    category: "Self-care",
    isCompleted: false,
  },
  {
    id: 16,
    name: "Visit a museum",
    caption: "Visit a local museum or art exhibit for culture and education",
    category: "Entertainment",
    isCompleted: false,
  },
  {
    id: 17,
    name: "Take dog for a walk",
    caption: "Take the dog for a 30-minute walk around the park",
    category: "Pets",
    isCompleted: false,
  },
  {
    id: 18,
    name: "Attend online class",
    caption:
      "Attend an online class or webinar for personal or professional growth",
    category: "Education",
    isCompleted: true,
  },
  {
    id: 19,
    name: "Schedule car maintenance",
    caption: "Make an appointment for routine car maintenance",
    category: "Automotive",
    isCompleted: false,
  },
  {
    id: 20,
    name: "Study for exam",
    caption: "Review notes and study materials for an upcoming exam or test",
    category: "Education",
    isCompleted: true,
  },
  {
    id: 21,
    name: "Clean bathroom",
    caption: "Clean and sanitize the bathroom",
    category: "Cleaning",
    isCompleted: false,
  },
  {
    id: 22,
    name: "Practice meditation",
    caption: "Spend 10 minutes meditating for mental clarity and relaxation",
    category: "Self-care",
    isCompleted: false,
  },
  {
    id: 23,
    name: "Buy a gift",
    caption: "Find and purchase a gift for a friend or family member",
    category: "Gifts",
    isCompleted: true,
  },
  {
    id: 24,
    name: "Update resume",
    caption: "Revise and update resume for job search",
    category: "Career",
    isCompleted: false,
  },
  {
    id: 25,
    name: "Water plants",
    caption: "Water and care for indoor or outdoor plants",
    category: "Gardening",
    isCompleted: false,
  },
  {
    id: 26,
    name: "Listen to a podcast",
    caption: "Listen to a podcast for entertainment or education",
    category: "Entertainment",
    isCompleted: true,
  },
  {
    id: 27,
    name: "Clean kitchen",
    caption: "Clean and organize the kitchen",
    category: "Cleaning",
    isCompleted: false,
  },
  {
    id: 28,
    name: "Buy new shoes",
    caption: "Find and purchase a new pair of shoes",
    category: "Shopping",
    isCompleted: false,
  },
  {
    id: 29,
    name: "Try a new hobby",
    caption: "Experiment with a new hobby or activity",
    category: "Personal Development",
    isCompleted: false,
  },
  {
    id: 30,
    name: "Update social media profile",
    caption: "Update profile information and photos on social media",
    category: "Technology",
    isCompleted: false,
  },
];
